name: Lint

on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - master

env:
  CI: true

jobs:
  install_dependencies:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install

  source:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Source
    runs-on: ubuntu-latest
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: ESLint
        run: yarn lint:js
        working-directory: ./ember-resources

  test_app:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Test App
    runs-on: ubuntu-latest
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: ESLint
        run: yarn lint:js
        working-directory: ./testing/ember-app

  tooling:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Tooling
    runs-on: ubuntu-latest
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Semantic Release
        run: yarn semantic-release --dry-run
        working-directory: ./ember-resources
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # docs:
  #   if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
  #   name: Docs
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: volta-cli/action@v1

  #   - run: yarn install
  #   - run: yarn lint:docs


  # docs-js-code:
  #   if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
  #   name: Docs (JS Code Samples)
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: volta-cli/action@v1

  #   - run: yarn install
  #   - run: yarn lint:docs-js

  commits:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Commit Messages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: volta-cli/action@v1
    - uses: wagoid/commitlint-github-action@v4.1.9
